使用try和catch关键字可以捕获异常。可以放在异常可能发生的地方，此代码块内的代码被称为保护代码。

    try
    {
       // 程序代码
    }catch(ExceptionName e1)
    {
       //Catch 块
    }
    
Catch语句包含要捕获异常类型的声明。当保护代码块中发生一个异常时，try后面的catch块就会被检查。
如果异常包含在catch块中，异常会被传递到该catch块，这和传递一个参数到方法时一样的。